import { StyleSheet } from "react-native";

export const aiChatStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerBackground: {
    height: 127,
    width: '100%',
    justifyContent: 'center',
  },
  backButton: {
    marginLeft: 18,
    marginTop: 38,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: -20,
    paddingHorizontal: 20,
    paddingBottom: 80, // Add padding to account for tab bar
  },
  handleContainer: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  handle: {
    width: 57,
    height: 7,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 30,
  },
  dishTitle: {
    fontSize: 18,
    fontWeight: '500',
    color: '#202026',
    marginVertical: 15,
  },
  imageContainer: {
    marginBottom: 15,
  },
  dishImage: {
    width: '100%',
    height: 160,
    borderRadius: 10,
  },
  ingredientsContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(124, 124, 124, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF6A00',
    marginBottom: 10,
  },
  ingredientsList: {
    fontSize: 12,
    lineHeight: 18,
    color: '#6A6A6A',
    marginBottom: 10,
  },
  editButton: {
    alignSelf: 'flex-end',
    backgroundColor: '#202026',
    borderRadius: 30,
    paddingVertical: 3,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    width: 84,
    height: 27,
  },
  editButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  recipeCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    marginBottom: 15,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(124, 124, 124, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    height: 121,
  },
  recipeImage: {
    width: 110,
    height: '100%',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  recipeContent: {
    flex: 1,
    padding: 10,
  },
  recipeTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#202026',
    marginBottom: 5,
  },
  recipeDescription: {
    fontSize: 10,
    lineHeight: 15,
    color: '#6A6A6A',
    marginBottom: 10,
  },
  recipeDetails: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 10,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 15,
  },
  detailText: {
    fontSize: 9,
    color: '#6A6A6A',
    marginLeft: 5,
  },
  heartButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 25,
    height: 25,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.2,
    borderColor: '#A3A3A3',
  },
  actionButtonsContainer: {
    marginVertical: 20,
  },
  externalLinkButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  externalButton: {
    width: '48%',
    height: 44,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#ECECEC',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 2,
  },
  youtubeIcon: {
    width: 36,
    height: 36,
    backgroundColor: '#FF0000',
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  youtubeIconText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  googleIcon: {
    width: 26,
    height: 26,
    backgroundColor: '#4285F4',
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  googleIconText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  externalButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6A6A6A',
  },
  circleButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  circleButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#202026',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
});