import { StyleSheet } from "react-native";

export const challengeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    paddingBottom: 80, // Add padding to account for tab bar
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "500",
    color: "#202026",
  },
  activeChallengeContainer: {
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "500",
    color: "#202026",
    marginBottom: 15,
  },
  activeChallenge: {
    height: 200,
    borderRadius: 15,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  activeChallengeImage: {
    width: "100%",
    height: "100%",
  },
  activeChallengeOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "flex-end",
  },
  activeChallengeContent: {
    padding: 16,
  },
  badgeContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FF6A00",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginBottom: 10,
  },
  badgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
    marginLeft: 5,
  },
  activeChallengeTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 10,
  },
  progressContainer: {
    marginBottom: 15,
  },
  progressBar: {
    height: 8,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 4,
    marginBottom: 5,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#FF6A00",
    borderRadius: 4,
  },
  progressText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  continueButton: {
    backgroundColor: "#FFFFFF",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  continueButtonText: {
    color: "#202026",
    fontSize: 14,
    fontWeight: "600",
  },
  weeklyChallengesContainer: {
    paddingHorizontal: 16,
    flex: 1,
  },
  challengeCard: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    marginBottom: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: "rgba(124, 124, 124, 0.1)",
    height: 120,
  },
  challengeImage: {
    width: 100,
    height: "100%",
  },
  challengeContent: {
    flex: 1,
    padding: 12,
    justifyContent: "space-between",
  },
  challengeBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FF6A00",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    alignSelf: "flex-start",
    marginBottom: 5,
  },
  challengeBadgeText: {
    color: "#FFFFFF",
    fontSize: 8,
    fontWeight: "600",
    marginLeft: 3,
  },
  challengeTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#202026",
    marginBottom: 4,
  },
  challengeDescription: {
    fontSize: 10,
    color: "#6A6A6A",
    marginBottom: 8,
    flex: 1,
  },
  challengeDetails: {
    flexDirection: "row",
    alignItems: "center",
  },
  detailItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 16,
  },
  detailText: {
    fontSize: 10,
    color: "#6A6A6A",
    marginLeft: 4,
  },
  heartButton: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 25,
    height: 25,
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.2,
    borderColor: "#A3A3A3",
  },
});