import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    paddingBottom: 80, // Add padding to account for tab bar
  },
  headerBackground: {
    height: 214,
    width: "100%",
  },
  headerOverlay: {
    height: "100%",
    width: "100%",
    paddingHorizontal: 16,
    paddingTop: 60,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  greeting: {
    fontSize: 20,
    lineHeight: 23,
    color: "#FFFFFF",
    fontWeight: "400",
  },
  welcomeBack: {
    fontSize: 20,
    lineHeight: 23,
    color: "#FFFFFF",
    fontWeight: "400",
    marginTop: 4,
  },
  headerIcons: {
    flexDirection: "row",
  },
  iconButton: {
    marginLeft: 15,
  },
  locationContainer: {
    marginTop: 30,
  },
  locationLabel: {
    fontSize: 14,
    lineHeight: 16,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
  },
  locationText: {
    fontSize: 18,
    lineHeight: 21,
    color: "#FFFFFF",
    fontWeight: "500",
    marginRight: 4,
  },
  finderCardsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: 20,
  },
  finderCard: {
    width: (width - 40) / 2,
    height: 74,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(108, 108, 108, 0.15)",
  },
  finderIconContainer: {
    marginRight: 10,
  },
  finderIcon: {
    fontSize: 24,
  },
  finderText: {
    fontSize: 16,
    lineHeight: 19,
    color: "#868686",
    fontWeight: "500",
  },
  featuredContainer: {
    marginTop: 20,
    paddingHorizontal: 16,
  },
  featuredGradient: {
    borderRadius: 15,
    height: 198,
    overflow: "hidden",
  },
  featuredContent: {
    flexDirection: "row",
    padding: 16,
    height: "100%",
  },
  featuredLeft: {
    flex: 1,
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  featuredTitle: {
    fontSize: 16,
    lineHeight: 19,
    color: "#202026",
    fontWeight: "500",
    marginBottom: 10,
  },
  featuredDishName: {
    fontSize: 14,
    lineHeight: 21,
    color: "#6A6A6A",
    fontWeight: "600",
    width: "80%",
  },
  cookNowButton: {
    backgroundColor: "#202026",
    borderRadius: 30,
    paddingVertical: 7,
    paddingHorizontal: 15,
    alignItems: "center",
    justifyContent: "center",
    width: 100,
    marginTop: 20,
  },
  cookNowText: {
    fontSize: 14,
    lineHeight: 21,
    color: "#FFFFFF",
    fontWeight: "800",
  },
  streakContainer: {
    width: 190,
    height: 177,
    marginLeft: 10,
    justifyContent: "flex-start",
  },
  streakTitle: {
    fontSize: 16,
    lineHeight: 19,
    color: "#202026",
    fontWeight: "500",
    marginBottom: 5,
  },
  streakCard: {
    width: 157,
    height: 43,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 10,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 3,
    marginTop: 5,
  },
  streakText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#6A6A6A",
    fontWeight: "600",
  },
  streakProgressContainer: {
    alignItems: "flex-end",
    marginTop: 15,
  },
  streakProgressBg: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#B5B5B5",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  streakProgressFill: {
    width: 57.2,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FF6A00",
    alignItems: "center",
    justifyContent: "center",
  },
  streakCount: {
    fontSize: 18,
    lineHeight: 21,
    color: "#202026",
    fontWeight: "500",
  },
  suggestionsContainer: {
    marginTop: 20,
    paddingHorizontal: 16,
    marginBottom: 30,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    lineHeight: 21,
    color: "#202026",
    fontWeight: "500",
  },
  sortButton: {
    width: 30,
    height: 30,
    backgroundColor: "#FFFFFF",
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(124, 124, 124, 0.1)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 2,
  },
  sortIcon: {
    fontSize: 18,
    color: "#202026",
  },
  recipesContainer: {
    paddingBottom: 10,
  },
  recipeCard: {
    width: 112,
    height: 132,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginRight: 15,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(124, 124, 124, 0.15)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  recipeImage: {
    width: "100%",
    height: 72,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  recipeContent: {
    padding: 8,
  },
  recipeTitle: {
    fontSize: 12,
    lineHeight: 15,
    color: "#202026",
    fontWeight: "600",
    marginBottom: 5,
  },
  recipeDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  recipeDetail: {
    flexDirection: "row",
    alignItems: "center",
  },
  detailText: {
    fontSize: 10,
    lineHeight: 12,
    color: "#6A6A6A",
    fontWeight: "500",
    marginLeft: 4,
  },
  heartButton: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0.2,
    borderColor: "#A3A3A3",
  },
  pagination: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  paginationDot: {
    width: 6,
    height: 6,
    borderRadius: 15,
    backgroundColor: "#B5B5B5",
    marginHorizontal: 3,
  },
  activeDot: {
    backgroundColor: "rgba(32, 32, 38, 0.4)",
  },
});